FROM python:3.8-slim

WORKDIR /app

# Install OS dependencies
RUN apt-get update && \
  apt-get install -y libsndfile1 && \
  apt-get install -y libgomp1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy only the requirements and install Python dependencies
COPY server/requirements_server.txt .
RUN pip install --no-cache-dir -r requirements_server.txt

# Copy only necessary files
COPY server/sa_speech_test.json .
COPY generated/audio_transcription_pb2.py .
COPY generated/audio_transcription_pb2_grpc.py .
COPY server/ .

CMD ["python", "server.py"]




