FROM python:3.8-slim

WORKDIR /app

# Install OS dependencies
RUN apt-get update && \
  apt-get install -y libsndfile1 ffmpeg && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy only the requirements and install Python dependencies
COPY client/requirements_client.txt .
RUN pip install --no-cache-dir -r requirements_client.txt

# Copy only necessary files
COPY generated/audio_transcription_pb2.py .
COPY generated/audio_transcription_pb2_grpc.py .
COPY client/ .

CMD ["python", "client.py"]
