FROM python:3.9

WORKDIR /app
ENV PYTHONPATH /app:$PYTHONPATH

# Install OS dependencies
RUN apt-get update && \
  apt-get install -y libsndfile1 libgomp1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy only the requirements and install Python dependencies
COPY AIPrivateInterfaceService/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy only necessary files
COPY AIPrivateInterfaceService/ .
COPY proto/Generated/Declarations/ /app/Declarations/

CMD ["python", "server.py"]





